#include "GpuSnapshot.h"
#include <cuda_runtime.h>

// Helper to avoid type mismatch with uint64_t
__device__ uint64_t min_u64(uint64_t a, uint64_t b) {
    return (a < b) ? a : b;
}

extern "C" __global__ void simulateMarketImpact(
    const GpuPriceLevel* bids, int bid_levels,
    const GpuPriceLevel* asks, int ask_levels,
    const uint64_t* order_sizes, // Array of simulated order sizes (generated by CPU)
    double* results,             // Output: average execution price per simulation
    int num_simulations,
    bool is_buy                  // true = sweep asks, false = sweep bids
) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= num_simulations) return;

    uint64_t target_qty = order_sizes[idx];
    uint64_t filled_qty = 0;
    uint64_t cost_basis = 0; 

    if (is_buy) {
        // Sweep asks from best price (index 0) to worst
        for (int i = 0; i < ask_levels && filled_qty < target_qty; ++i) {
            uint64_t available = asks[i].quantity;
            uint64_t take = min_u64(available, target_qty - filled_qty);
            cost_basis += take * asks[i].price;
            filled_qty += take;
        }
    } else {
        // Sweep bids from best price (index 0) to worst
        for (int i = 0; i < bid_levels && filled_qty < target_qty; ++i) {
            uint64_t available = bids[i].quantity;
            uint64_t take = min_u64(available, target_qty - filled_qty);
            cost_basis += take * bids[i].price;
            filled_qty += take;
        }
    }

    // Calculate weighted average execution price
    results[idx] = (filled_qty > 0) ? (double)cost_basis / (double)filled_qty : 0.0;
}